### ISSUE TITLE
user info bug

### ISSUE THREAD

**Issue by symbyte** [colegarien/SDDTermProject#67]
Signing up as a new user after having been logged in as a different user causes previous users info to be displayed in user info.

To reproduce:
1. log in as some user already in the sytem
2. go to sign up screen and create new user. 
3. click user info and see previous user's information instead of new user's information

**Comment by nelalison** [comment]
@liveyourheart 
A user should not be able to access the sign_up page when logged in. If they try going back to access it, they need to be logged out automatically. To do this you need to access the back stack on the android device in order to clear there shared preferences whenever they try going back beyond there logged in home interface.
